stages:
  - build

build:
  stage: build
  image: python:3.8
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pyinstaller
    - pyinstaller --onefile your_script.py
  artifacts:
    paths:
      - dist/your_script.exe